require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CatesController do

  # This should return the minimal set of attributes required to create a valid
  # Cate. As you add validations to Cate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CatesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cates as @cates" do
      cate = Cate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cates).should eq([cate])
    end
  end

  describe "GET show" do
    it "assigns the requested cate as @cate" do
      cate = Cate.create! valid_attributes
      get :show, {:id => cate.to_param}, valid_session
      assigns(:cate).should eq(cate)
    end
  end

  describe "GET new" do
    it "assigns a new cate as @cate" do
      get :new, {}, valid_session
      assigns(:cate).should be_a_new(Cate)
    end
  end

  describe "GET edit" do
    it "assigns the requested cate as @cate" do
      cate = Cate.create! valid_attributes
      get :edit, {:id => cate.to_param}, valid_session
      assigns(:cate).should eq(cate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cate" do
        expect {
          post :create, {:cate => valid_attributes}, valid_session
        }.to change(Cate, :count).by(1)
      end

      it "assigns a newly created cate as @cate" do
        post :create, {:cate => valid_attributes}, valid_session
        assigns(:cate).should be_a(Cate)
        assigns(:cate).should be_persisted
      end

      it "redirects to the created cate" do
        post :create, {:cate => valid_attributes}, valid_session
        response.should redirect_to(Cate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cate as @cate" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cate.any_instance.stub(:save).and_return(false)
        post :create, {:cate => {}}, valid_session
        assigns(:cate).should be_a_new(Cate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cate.any_instance.stub(:save).and_return(false)
        post :create, {:cate => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cate" do
        cate = Cate.create! valid_attributes
        # Assuming there are no other cates in the database, this
        # specifies that the Cate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => cate.to_param, :cate => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested cate as @cate" do
        cate = Cate.create! valid_attributes
        put :update, {:id => cate.to_param, :cate => valid_attributes}, valid_session
        assigns(:cate).should eq(cate)
      end

      it "redirects to the cate" do
        cate = Cate.create! valid_attributes
        put :update, {:id => cate.to_param, :cate => valid_attributes}, valid_session
        response.should redirect_to(cate)
      end
    end

    describe "with invalid params" do
      it "assigns the cate as @cate" do
        cate = Cate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cate.any_instance.stub(:save).and_return(false)
        put :update, {:id => cate.to_param, :cate => {}}, valid_session
        assigns(:cate).should eq(cate)
      end

      it "re-renders the 'edit' template" do
        cate = Cate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cate.any_instance.stub(:save).and_return(false)
        put :update, {:id => cate.to_param, :cate => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cate" do
      cate = Cate.create! valid_attributes
      expect {
        delete :destroy, {:id => cate.to_param}, valid_session
      }.to change(Cate, :count).by(-1)
    end

    it "redirects to the cates list" do
      cate = Cate.create! valid_attributes
      delete :destroy, {:id => cate.to_param}, valid_session
      response.should redirect_to(cates_url)
    end
  end

end
